services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WerkraumMedia\Watchlist\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'

  WerkraumMedia\Watchlist\Session\CookieSessionService:
    # Has state and needs to be shared in order to provide this state to middleware
    shared: true
