services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WerkraumMedia\Watchlist\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Extbase/TypeConverter/*'

  WerkraumMedia\Watchlist\Session\CookieSessionService:
    # Has state and needs to be shared in order to provide this state to middleware
    shared: true

  WerkraumMedia\Watchlist\Form\Hook\BeforeRenderingHook:
    public: true

  WerkraumMedia\Watchlist\Extbase\TypeConverter\ItemTypeConverter:
    tags:
      - name: 'extbase.type_converter'
        priority: 10
        target: 'WerkraumMedia\Watchlist\Domain\Model\Item'
        sources: 'string'

  WerkraumMedia\Watchlist\Extbase\TypeConverter\WatchlistTypeConverter:
    tags:
      - name: 'extbase.type_converter'
        priority: 10
        target: 'WerkraumMedia\Watchlist\Domain\Model\Watchlist'
        sources: 'string'
