name: CI

on:
  - pull_request

jobs:
  check-composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Validate composer.json
        run: nix-shell --pure --run project-validate-composer

  php-linting:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 8.2
          - 8.3
          - 8.4
          - 8.5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none
          tools: composer:v2
          ini-values: register_argc_argv=ON

      - name: PHP lint
        run: "find *.php Classes Configuration Tests -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l"

  xml-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Validate XML
        run: nix-shell --pure --run project-validate-xml

  coding-guideline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check Coding Guideline
        run: nix-shell --pure --run project-coding-guideline

  code-quality:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: '8.2'
          - php-version: '8.3'
          - php-version: '8.4'
          - php-version: '8.5'
    steps:
      - uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none
          tools: composer:v2
          ini-values: register_argc_argv=ON

      - name: Install dependencies
        run: |-
          composer update --no-interaction --prefer-dist --no-progress
          ./vendor/bin/codecept build

      - name: Code Quality (by PHPStan)
        run: ./vendor/bin/phpstan analyse

  tests-mysql:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: '8.2'
            typo3-version: '^13.0'
          - php-version: '8.3'
            typo3-version: '^13.0'
          - php-version: '8.4'
            typo3-version: '^13.0'
          - php-version: '8.5'
            typo3-version: '^13.0'
          - php-version: '8.2'
            typo3-version: '^14.0'
          - php-version: '8.3'
            typo3-version: '^14.0'
          - php-version: '8.4'
            typo3-version: '^14.0'
          - php-version: '8.5'
            typo3-version: '^14.0'
    steps:
      - uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none
          tools: composer:v2
          ini-values: register_argc_argv=ON

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8'
          mysql database: 'typo3'
          mysql root password: 'root'

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --password=root --silent; do
            sleep 1
          done

      - name: Install dependencies with expected TYPO3 version
        run: composer require --prefer-dist --no-progress "typo3/cms-backend:${{ matrix.typo3-version }}" "typo3/cms-core:${{ matrix.typo3-version }}" "typo3/cms-extbase:${{ matrix.typo3-version }}" "typo3/cms-fluid-styled-content:${{ matrix.typo3-version }}" "typo3/cms-form:${{ matrix.typo3-version }}" "typo3/cms-frontend:${{ matrix.typo3-version }}"

      - name: PHPUnit Tests
        env:
          typo3DatabaseDriver: "pdo_mysql"
          typo3DatabaseName: "typo3"
          typo3DatabaseHost: "127.0.0.1"
          typo3DatabaseUsername: "root"
          typo3DatabasePassword: "root"
        run: ./vendor/bin/phpunit --testdox

  tests-acceptance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run Acceptance Tests
        run: nix-shell --pure --run project-test-acceptance
